### ISSUE TITLE
About reproducing results

### ISSUE THREAD

**Issue by Talnex** [zouzhenhong98/SensatUrban-BEV-Seg3D#1]
Thank you so much for your great work
When I train according to the readme process, the model always fails to achieve the same curve as img/single_scale_training.png
My experimental configuration is:
2 x 2080ti and batchsize=4
miou can only be up to 41% in the validation set

<img width="1476" alt="iShot2022-09-09 10 17 07" src="https://user-images.githubusercontent.com/33219211/189258142-22dcb82d-e440-4f35-b77b-1462197597c6.png">

In addition, can you also provide pre-trained weights?
thank you very much

**Comment by Talnex** [comment]
I noticed that when generating the dataset, the alt image was lost in accuracy because it was saved as png, so I changed the relevant code

**Comment by zhanwenxiao** [comment]
> I noticed that when generating the dataset, the alt image was lost in accuracy because it was saved as png, so I changed the relevant code

Hello, I meet the same results, too.  Have you reproduced the results? What's more, I have not found OCRNet-HRNet in code

**Comment by BKINGING** [comment]
> I noticed that when generating the dataset, the alt image was lost in accuracy because it was saved as png, so I changed the relevant code

Excuse me, I met this situation what should I do?python train.py --use-balanced-weights --batch-size 8 --base-size 500 --crop-size 500 --loss-type focal --epochs 200 --eval-interval 1
Namespace(base_size=500, batch_size=8, checkname='Res-Unet', crop_size=500, cuda=True, dataset='cityscapes', epochs=200, eval_interval=1, ft=False, gpu_ids=[0, 1], loss_type='focal', lr=0.02, lr_scheduler='poly', momentum=0.9, nesterov=False, no_cuda=False, no_val=False, resume=None, seed=1, start_epoch=0, test_batch_size=8, use_balanced_weights=True, weight_decay=0.0001, workers=4)
  0%|                                                                                                                               | 0/13 [00:00<?, ?it/s]Calculating classes weights
  0%|                                                                                                                               | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 292, in <module>
    main()
  File "train.py", line 280, in main
    trainer = Trainer(args)
  File "train.py", line 49, in __init__
    weight = calculate_weigths_labels(args.dataset, self.train_loader, self.nclass)
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/utils/calculate_weights.py", line 38, in calculate_weigths_labels
    y = sample['label']
KeyError: 'label'

**Comment by BKINGING** [comment]
> > I noticed that when generating the dataset, the alt image was lost in accuracy because it was saved as png, so I changed the relevant code
> 
> Hello, I meet the same results, too. Have you reproduced the results? What's more, I have not found OCRNet-HRNet in code

Excuse me, I met this situation what should I do? python /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py
0it [00:00, ?it/s]loading 6 files

loading file /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/dataloaders/datasets/data_release/test/birmingham_block_2.ply[00:00<?, ?it/s]
  0%|                                                                                                                                | 0/6 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 641, in <module>
    Sensat.evaluate_batch(Sensat.evaluate_batch_nn(Sensat.eval_offline_img2pts))
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 624, in evaluate_batch
    miou, iou_list, gt_list, oacc, macc = batch_mIoU(batch_iterator)
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/helper_metrics.py", line 83, in batch_mIoU
    for preds, gt in tqdm(iter_data):
  File "/home/hubu/anaconda3/envs/Segment/lib/python3.7/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 606, in evaluate_batch_nn
    ply_data = self.load_points(ply_path, reformat=True)
  File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 155, in load_points
    c = _ply_data["class"]
ValueError: no field of name class

**Comment by BKINGING** [comment]
> Thank you so much for your great work When I train according to the readme process, the model always fails to achieve the same curve as img/single_scale_training.png My experimental configuration is: 2 x 2080ti and batchsize=4 miou can only be up to 41% in the validation set
> 
> <img alt="iShot2022-09-09 10 17 07" width="1476" src="https://user-images.githubusercontent.com/33219211/189258142-22dcb82d-e440-4f35-b77b-1462197597c6.png">
> 
> In addition, can you also provide pre-trained weights? thank you very much

Excuse me, I met this situation what should I do? python /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py
0it [00:00, ?it/s]loading 6 files

loading file /media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/dataloaders/datasets/data_release/test/birmingham_block_2.ply[00:00<?, ?it/s]
0%| | 0/6 [00:00<?, ?it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 641, in
Sensat.evaluate_batch(Sensat.evaluate_batch_nn(Sensat.eval_offline_img2pts))
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 624, in evaluate_batch
miou, iou_list, gt_list, oacc, macc = batch_mIoU(batch_iterator)
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/helper_metrics.py", line 83, in batch_mIoU
for preds, gt in tqdm(iter_data):
File "/home/hubu/anaconda3/envs/Segment/lib/python3.7/site-packages/tqdm/std.py", line 1182, in iter
for obj in iterable:
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 606, in evaluate_batch_nn
ply_data = self.load_points(ply_path, reformat=True)
File "/media/hubu/Data1/202131116023006_bky/SensatUrban-BEV-Seg3D-main/preprocess/point_EDA_31.py", line 155, in load_points
c = _ply_data["class"]
ValueError: no field of name class
